counter1 = Counter.create({name: "Halo Reqs, Helms left", amount: 30, description: "Halo unlocks, common to rare only"})
counter2 = Counter.create({name: "Halo Reqs, Armors left", amount: 24, description: "Halo unlocks, common to rare only"})
counter3 = Counter.create({name: "Halo Reqs, Visors left", amount: 15, description: "Halo unlocks, common to rare only"})
counter4 = Counter.create({name: "Halo Reqs, Stances left", amount: 5, description: "Halo unlocks, common to rare only"})
counter5 = Counter.create({name: "Halo Reqs, Assassinations left", amount: 2, description: "Halo unlocks, common to rare only"})
counter6 = Counter.create({name: "Halo Reqs, Weapon Skins left", amount: 19, description: "Halo unlocks, common to rare only"})
counter7 = Counter.create({name: "Halo Reqs, Loadout Weapons left", amount: 22, description: "Halo unlocks, common to rare only"})
counter8 = Counter.create({name: "Halo Reqs, Emblems left", amount: 53, description: "Halo unlocks, common to rare only"})

tag1 = Tag.create({name: "Games"})
tag2 = Tag.create({name: "Video Games"})

countertag1 = CounterTag.create({counter_id: counter1.id, tag_id: tag1.id})
countertag2 = CounterTag.create({counter_id: counter1.id, tag_id: tag2.id})
countertag3 = CounterTag.create({counter_id: counter2.id, tag_id: tag1.id})
countertag4 = CounterTag.create({counter_id: counter2.id, tag_id: tag2.id})
countertag5 = CounterTag.create({counter_id: counter3.id, tag_id: tag1.id})
countertag6 = CounterTag.create({counter_id: counter3.id, tag_id: tag2.id})
countertag7 = CounterTag.create({counter_id: counter4.id, tag_id: tag1.id})
countertag8 = CounterTag.create({counter_id: counter4.id, tag_id: tag2.id})
countertag9 = CounterTag.create({counter_id: counter5.id, tag_id: tag1.id})
countertag10 = CounterTag.create({counter_id: counter5.id, tag_id: tag2.id})
countertag11 = CounterTag.create({counter_id: counter6.id, tag_id: tag1.id})
countertag12 = CounterTag.create({counter_id: counter6.id, tag_id: tag2.id})
countertag13 = CounterTag.create({counter_id: counter7.id, tag_id: tag1.id})
countertag14 = CounterTag.create({counter_id: counter7.id, tag_id: tag2.id})
countertag15 = CounterTag.create({counter_id: counter8.id, tag_id: tag1.id})
countertag16 = CounterTag.create({counter_id: counter8.id, tag_id: tag2.id})